# Generated by Django 6.0.7 on 2026-07-08 09:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0002_alter_tag_options_alter_tag_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('summary', models.TextField(blank=True)),
                ('mood', models.CharField(blank=True, choices=[('amazing', 'Amazing'), ('good', 'Good'), ('neutral', 'Neutral'), ('sad', 'Sad'), ('anxious', 'Anxious'), ('angry', 'Angry'), ('exhausted', 'Exhausted')], max_length=20)),
                ('energy_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('stress_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gratitude', models.TextField(blank=True)),
                ('todays_wins', models.TextField(blank=True)),
                ('challenges', models.TextField(blank=True)),
                ('lessons_learned', models.TextField(blank=True)),
                ('tomorrow_focus', models.TextField(blank=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_pinned', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='published', max_length=20)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('shared', 'Shared'), ('public', 'Public')], default='private', max_length=20)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('reading_time', models.PositiveIntegerField(default=0)),
                ('ai_processed', models.BooleanField(default=False)),
                ('ai_summary', models.TextField(blank=True)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('writing_score', models.FloatField(blank=True, null=True)),
                ('ai_tags', models.JSONField(blank=True, default=list)),
                ('ai_last_processed', models.DateTimeField(blank=True, null=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='journal_entries', to='tags.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalImage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='journal_images/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='journal.journalentry')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['user', 'status'], name='journal_jou_user_id_f28f63_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['user', 'created_at'], name='journal_jou_user_id_9e5be0_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['user', 'is_favorite'], name='journal_jou_user_id_a2ab11_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['user', 'is_pinned'], name='journal_jou_user_id_215934_idx'),
        ),
    ]
