# Generated by Django 6.0.7 on 2026-07-09 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_journalentry_import_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='mood',
            field=models.CharField(blank=True, choices=[('happy', 'Happy'), ('neutral', 'Neutral'), ('sad', 'Sad'), ('excited', 'Excited'), ('tired', 'Tired'), ('motivated', 'Motivated'), ('inspired', 'Inspired')], max_length=20),
        ),
    ]
