# Generated by Django 6.0.7 on 2026-07-08 09:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0002_alter_tag_options_alter_tag_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('achievement', 'Achievement'), ('career', 'Career'), ('education', 'Education'), ('health', 'Health'), ('fitness', 'Fitness'), ('travel', 'Travel'), ('relationship', 'Relationship'), ('finance', 'Finance'), ('project', 'Project'), ('personal', 'Personal'), ('milestone', 'Milestone'), ('celebration', 'Celebration'), ('other', 'Other')], default='other', max_length=50)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('shared', 'Shared'), ('public', 'Public')], default='private', max_length=20)),
                ('favorite', models.BooleanField(default=False)),
                ('pinned', models.BooleanField(default=False)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('tags', models.ManyToManyField(blank=True, related_name='memories', to='tags.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemoryImage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='memory_images/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='journey.memory')),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='memory',
            index=models.Index(fields=['user', 'date'], name='journey_mem_user_id_5a65cd_idx'),
        ),
        migrations.AddIndex(
            model_name='memory',
            index=models.Index(fields=['user', 'category'], name='journey_mem_user_id_9e3319_idx'),
        ),
        migrations.AddIndex(
            model_name='memory',
            index=models.Index(fields=['user', 'favorite'], name='journey_mem_user_id_034c91_idx'),
        ),
        migrations.AddIndex(
            model_name='memory',
            index=models.Index(fields=['user', 'pinned'], name='journey_mem_user_id_f8f269_idx'),
        ),
    ]
