# Generated by Django 6.0.7 on 2026-07-08 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_task_goal_alter_subtask_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='import_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
    ]
